/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package x.si.pkg0;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Necazu
 */
public class frame0 extends javax.swing.JFrame {

    /**
     * Creates new form frame0
     */
    
    public frame0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cont = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(162, 171, 70));
        jLabel1.setText("X & O");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 171, 70));
        jLabel2.setText("Nume Jucator O :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(162, 171, 70));
        jLabel3.setText("Nume Jucator X :");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Start joc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(43, 56, 22));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(166, 179, 37));

        jTextField2.setBackground(new java.awt.Color(43, 56, 22));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(166, 179, 37));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("Dark Mode joc");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cont.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cont.setText("Creeaza cont");
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(cont))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String n1=jTextField1.getText();
        String n2=jTextField2.getText();
    
            
         if(n1.equals("") && n2.equals(""))
                    {
                       setVisible(false);
                       frame1 frame = new frame1("Jucator X","Jucator O",1);
                       frame.setVisible(true);
                       frame.setPreferredSize(new Dimension(600, 350));
                       frame.getContentPane().setBackground(Color.BLACK);
                       frame.setDefaultCloseOperation(frame1.EXIT_ON_CLOSE);
                       frame.pack();
                    }
       else
        {
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/x_si_o?useSSL=false","root","Unu2trei4");

                    


                    Statement stm= con.createStatement();

                    String sql="select*from topuri where nume in ('"+n1+"', '"+n2+"')";
                   
                    ResultSet rs =stm.executeQuery(sql);
                   
                    if(rs.next() )
                    {
                        setVisible(false);
                        frame1 frame = new frame1(n1,n2,1);
                        frame.setVisible(true);
                        frame.setPreferredSize(new Dimension(600, 350));
                        frame.getContentPane().setBackground(Color.BLACK);
                        frame.setDefaultCloseOperation(frame1.EXIT_ON_CLOSE);
                        frame.pack();
                    }
                    else
                        {
                            JOptionPane.showMessageDialog(this, "Nu aveti cont!");
                            jTextField1.setText("");
                             jTextField2.setText("");
                        }
                }catch(Exception e)
                    {
                        System.out.println(e.getMessage());
                    }    
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String n1=jTextField1.getText();
        String n2=jTextField2.getText();
    
            
         if(n1.equals("")&& n2.equals(""))
                    {
                       setVisible(false);
                        frame1 frame = new frame1("Jucator X","Jucator O");
                        frame.setVisible(true);
                        frame.setPreferredSize(new Dimension(600, 350));
                        frame.getContentPane().setBackground(new Color(32, 40, 79));
                        frame.setDefaultCloseOperation(frame1.EXIT_ON_CLOSE);
                        frame.pack();
                    }
       else
        {
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/x_si_o?useSSL=false","root","Unu2trei4");
                    
                    Statement stm= con.createStatement();

                    String sql="select*from topuri where nume in ('"+n1+"', '"+n2+"')";
                   
                    ResultSet rs =stm.executeQuery(sql);
                   
                    if(rs.next() )
                    {
                        setVisible(false);
                        frame1 frame = new frame1(n1,n2);
                        frame.setVisible(true);
                        frame.setPreferredSize(new Dimension(600, 350));
                        frame.getContentPane().setBackground(new Color(32, 40, 79));
                        frame.setDefaultCloseOperation(frame1.EXIT_ON_CLOSE);
                        frame.pack();
                    }
                    else
                        {
                            JOptionPane.showMessageDialog(this, "Nu aveti cont!");
                            jTextField1.setText("");
                             jTextField2.setText("");
                        }
                }catch(Exception e)
                    {
                        System.out.println(e.getMessage());
                    }    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
        // TODO add your handling code here:
            int scorx=0,scoro=0;
            String n1=jTextField1.getText();
            String n2=jTextField2.getText();
    
            
         if(n1.equals("") && n2.equals("") || !n1.equals("") && n2.equals("")|| n1.equals("") && !n2.equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "Completati numele jucatorilor!");
                            jTextField1.setText("");
                            jTextField2.setText("");
                    }
       else
        {
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/x_si_o?useSSL=false","root","Unu2trei4");

                    Statement stm= con.createStatement();

                    String sql="insert into topuri values ('"+n1+"', '"+scorx+"'),('"+n2+"', '"+scoro+"');";
                   
                    int rs =stm.executeUpdate(sql);
                   
                    if(rs==1)
                    {
                        JOptionPane.showMessageDialog(this, "Error 404"+"\n"
                                        +"Numele alese exista deja in baza de date");
                        jTextField1.setText("");
                        jTextField2.setText("");
                    }
                    else
                        {
                             JOptionPane.showMessageDialog(this, "Conturile au fost create cu succes" + "\n"
                                             + "Puteti apasa START JOC!");
                        }
                }catch(Exception e)
                    {
                        System.out.println(e.getMessage());
                    }    
        }
 
    }//GEN-LAST:event_contActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cont;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
